dist: trusty
sudo: required
addons:
  sonarcloud:
    organization: urma-github
    token:
      secure: nM4I7Z/EPx33R7t+OY7g85zSrGApAl/UAzXfFJ9+jOIm1vDZnoPGnbSsLM2qtF0T1iEUNr9QVG2zLPYpGm2qDSyB1dfFUp7DZXLt3JimPq4SlAFvuarNV1lxlSpv/ylEoWjsMSBNqnq1/Jff0omtkpgrbNUcYTij0HZrPzDLGj0aG5lv4SeL9Gin39ZsGB7JJOX3VoKXxDSJ4y+xI8fLiCxj0h54RWvwzcLOlPmjnxwS5tH/2Eg3+h9bvUC8ew5KQE/0j2c9ojKyAubroMPxvc1E+VqaGIKkfzb0XFUg4bBlKBoUNd6+RTMSqvRrWQ7rDnum7zohho/3rJ3z5bx/y+FIQ/r7OPq3j+FwmAeIOodPTP0MrKFBPT9illwSsqg3nTYRS8WdphYgpkqik0FQNhoTDSF8zf0ZrsKQer+XpWh+DepO/AU0D43MGkmKrTtiGKKJCXDAZHLh0hLTjQ9cVfN8k5mxXTawwbe/yKWSGklHYXQGldnn3vMgYrYkndTiQ3QYHncjcvIBpgwY1BZEFmkvs0KfJTu+xEZ/IfDBqluaSrpgWtPxJrf8SrM7+s3+yC4xdzrx7zKdrfLDLFfJ9H8u5Kd3B+Y2hnPxW6zeDUWY9n1VEUtakH4trQ30ZRJ7cJ+GHbNzo+Ha1IdM579QiUlT461NbCLi0uQh+kb+n7o=
jdk:
- oraclejdk8
script:
- sonar-scanner
cache:
  directories:
  - "$HOME/.sonar/cache"
notifications:
  slack:
    secure: tCkHYYG1LEFlbtIXPjOvW5XcOkbGNMT9FA+I91/BR0+zcm3DP1CajI/tW1DPvYKmdVr92Vwam0yd7TkCnH13RU/C5dVXkxDlNBQrKvu18RmTO8NAv0F9y6MuCDgi+abpWX3mOkZvxJH+lWoSiG/rD+MtThB0NFz7xuDynJwSDb2H1tRY1DKzPw2d/IovNdlQyn7xxNz+oWSMPiYQTpVgZhUu6oDf9lA/W4vHh37HzeJtxbyXoUZFQLlqkG3uGqmfjO/Vmh6qk7/46mh55AH5p5M4lO1KIqj26dJyCfWBpkeoToiyWKCKZvig27f22yZBIEBllOy4W7eWhFspVGcitBhnrtGdsmecFQZeyXmNkLdeiL3ZMBH+97zY/3cdy5uBpobp1EnrZw1X29voHxeLIBM9GsNEeJ8H6AupMd4XggATSOqOwbz7QwcfQdI60gOgChaUmiwQ9Fq04FVvqUje1EvA6A/APbj789CZd8n/5Dyekz9s4z0jsD2jgoMUDttFUXsAbypfSK38ZKU2tIknpR9bGMgVFTWqnB6xrF+iUC2i6OycYCijbOO7lfgWACqoc/dxMRZku8dDNTG6WLtUrM038+RqjjsGMz5p0bxDLu47rTQKYSWFYn/e/p7U2Vh9wuXm75WGUZk4Bl0K4V6t3eeLbPRSz9VlzX7HpQ/bvRk=
